aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_controller

controller:
  xy:
    p_gain: 2.3
    i_gain: 0.02
    d_gain: 4.0
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 3.6
    i_gain: 1.55
    d_gain: 3.4
    limit_err_p: 1.0
    limit_sum: 16.5
    limit_p: 16.5
    limit_i: 16.5
    limit_d: 16.5
    landing_err_z: -0.55

  yaw:
    limit_sum: 6.0
    limit_p: 4.5
    limit_i: 4.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: false

  lqi:
    gain_generate_rate: 20.0 # a lit bit faster for desire_coodinate pub
    gyro_moment_compensation: true
    clamp_gain: true

    roll_pitch_p: 1100
    roll_pitch_i: 10
    roll_pitch_d: 80

    yaw_p: 100
    yaw_i: 0.5
    yaw_d: 50

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1

