motor_info:
        min_pwm: 0.5 # 1000 [ms]
        max_pwm: 0.85 # 1700 [ms]
        min_thrust: 2.0 #  [N]
        force_landing_thrust: 6.0 #[N]
        m_f_rate: -0.0157
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 4
        ref1:
                voltage: 24.2
                max_thrust: 21.37 # N 
                polynominal2: 0.164519167 # x10
                polynominal1: -16.225736115  # x10
                polynominal0: 40.4484933567 # x1
        ref2:
                voltage: 23.2
                max_thrust: 19.97 # N 
                polynominal2: 0.157560162 # x10
                polynominal1: -15.703193407  # x10
                polynominal0: 39.6576127189 # x1
        ref3:
                voltage: 22.2
                max_thrust: 18.44 # N 
                polynominal2: 0.145649905 # x10
                polynominal1: -14.480281285 # x10
                polynominal0: 36.4201880726 # x1
        ref4:
                voltage: 21.2
                max_thrust: 17.2 # N 
                polynominal2: 0.127998309 # x10
                polynominal1: -12.364605078  # x10
                polynominal0: 29.8408179290 # x1
