servo_controller:
  state_sub_topic: servo/states
  ctrl_pub_topic: servo/target_states
  torque_pub_topic: servo/torque_enable

joints:
  angle_sgn: 1
  angle_scale: 0.00076699
  zero_point_offset: 2047
  torque_scale: 1.0 # TODO please update the scale

  # for low pass filter
  filter_flag: true
  sample_freq: 50.0 # 50Hz
  cutoff_freq: 10.0 # 10Hz, test

  # for simulation
  simulation:
    pid: {p: 50.0, i: 0.01, d: 2.0}
    init_value: 0
    type: effort_controllers/JointPositionController

  # should be in order in terms of kinematics model
  # e.g. joint1 -> jointN; gimbal1_roll -> gimbal1_pitch
  controller1:
    id: 0
    name: joint1
  controller2:
    id: 1
    name: joint2
