aerial_robot_control_name: aerial_robot_control/tiger_walk

controller:

  control_verbose: false

  walk:
    joint_ctrl_rate: 10.0 # 10 Hz
    joint_torque_control_thresh: 2.0 # Nm
    servo_angle_bias: 0.02 # rad
    servo_max_torque: 6 # Nm
    servo_torque_change_rate: 2.0
    opposite_free_leg_joint_torque_control_mode: true

    xy:
      p_gain: 0.0 # N/m:
      i_gain: 0.0 #
      d_gain: 0.0
      limit_sum: 0.0
      limit_p: 0.0
      limit_i: 0.0
      limit_d: 0.0

    z:
      p_gain: 200.0 # N/m: 2N/0.01m
      i_gain: 0.0 # 20.0 N/m
      d_gain: 0.0
      limit_sum: 20.0
      limit_p: 20.0
      limit_i: 20.0
      limit_d: 20.0

    link:
      p_gain: 25.0 # N/rad: 0.2 rad -> 5 N
      i_gain: 0.0
      limit_sum: 5.0
      limit_p: 5.0
      limit_i: 5.0
      limit_d: 5.0
