aerial_robot_control_name: aerial_robot_control/tiger_walk

controller:

  control_verbose: false

  walk:
    joint_ctrl_rate: 10.0 # 10 Hz

    z:
      p_gain: 200.0 # N/m: 2N/0.01m
      i_gain: 0.0 # 20.0 N/m
      d_gain: 0.0
      limit_sum: 20.0
      limit_p: 20.0
      limit_i: 20.0
      limit_d: 10.0

