aerial_robot_control_name: aerial_robot_control/tiger_walk

controller:

  control_verbose: false

  walk:
    joint_ctrl_rate: 10.0 # 10 Hz
    joint_torque_control_thresh: 2.0 # Nm
    servo_angle_bias: 0.02 # rad
    servo_angle_bias_torque: 4 # Nm
    servo_max_torque: 6.5 # Nm
    servo_torque_change_rate: 2.0

    thrust_force_weight: 1.0
    joint_torque_weight: 1.0 # 10.0 ~ 20.0
    joint_static_torque_limit: 3.0
    raise_joint_static_torque_limit: 1.5 # < joint_static_torque_limit

    all_joint_position_control: true

    free_leg_torque_mode: false
    raise_separate_motion: true
    opposite_free_leg_joint_torque_control_mode: true
    raise_leg_large_torque_control: true
    lower_leg_speed: 0.5 # rad/s

    raise_leg_force_i_gain: 100.0 #  /s imediately
    modify_leg_force_i_gain: 0.0 # /s
    lower_leg_force_i_gain: 0.0 # /s
    contact_leg_force_i_gain: 1.0 # /s

    modify_leg_force_ratio_thresh: 0.9
    lower_leg_force_ratio_thresh: 0.9

    raise_leg_burst_p_gain: 0.0 # ration / rad. e.g.,  0.1 / 0.1
    raise_leg_burst_thresh: 0.1 # ratio
    raise_leg_burst_bias: 0.1 # rad

    check_interval: 0.1


    xy:
      p_gain: 0.0 # N/m:
      i_gain: 0.0 #
      d_gain: 0.0
      limit_sum: 0.0
      limit_p: 0.0
      limit_i: 0.0
      limit_d: 0.0

    z:
      p_gain: 200.0 # N/m: 2N/0.01m
      i_gain: 0.0 # 20.0 N/m
      d_gain: 0.0
      limit_sum: 20.0
      limit_p: 20.0
      limit_i: 20.0
      limit_d: 20.0

    link:
      p_gain: 25.0 # N/rad: 0.2 rad -> 5 N
      i_gain: 0.0
      limit_sum: 5.0
      limit_p: 5.0
      limit_i: 5.0
      limit_d: 5.0

    joint:
      joint_error_angle_thresh: 0.02 # rad

      p_gain: 20.0 # Nm/rad: 0.1 rad -> 2 Nm
      i_gain: 0.1
      limit_sum: 0.0
      limit_p: 4.0
      limit_i: 4.0
      limit_d: 4.0
