<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx_link" >

  <!-- D-H kai description(different from prof.nakamura) -->
  <xacro:macro name="hydrusx_link" params="self child rotor_direction with_leg:=1 with_battery:=1">

    <!-- link -->
    <link name="link${self}">
      <!-- head -->
      <xacro:if value="${self == 1}">
        <inertial>
          <origin xyz="${link_length* 0.5 + 0.055120} 0.0 0.011580" rpy="0 0 0"/>
          <mass value="0.566650"/>
          <inertia
              ixx="0.001804" iyy="0.017972" izz="0.019248"
              ixy="0.000021" ixz="0.000372" iyz="0.000000"/>
        </inertial>
        <xacro:link_model type="head" />
      </xacro:if>
      <xacro:unless value="${self == 1}">

        <!-- tail -->
        <xacro:if value="${self == child}">
          <inertial>
            <origin xyz="${link_length * 0.5 + -0.013450} 0.0 0.012830" rpy="0 0 0"/>
            <mass value="0.495530"/>
            <inertia
                ixx="0.001758" iyy="0.013619" izz="0.014910"
                ixy="0.000020" ixz="-0.000076" iyz="0.000000"/>
          </inertial>
          <xacro:link_model type="end" />
        </xacro:if>
        <xacro:unless value="${self == child}">
          <!-- general -->
          <inertial>
            <origin xyz="${link_length * 0.5 + 0.038190} 0.0 0.010950" rpy="0 0 0"/>
            <mass value="0.597720"/>
            <inertia
                ixx="0.001828" iyy="0.021127" izz="0.022388"
                ixy="0.000021" ixz="0.000260" iyz="0.000000"/>
          </inertial>
          <xacro:link_model type="general" />
        </xacro:unless>
      </xacro:unless>
    </link>

    <xacro:damping_factor link ="link${self}"/>

    <!-- rotor -->
    <joint name="rotor${self}" type="continuous">
      <limit effort="100.0" lower="0" upper="${max_force}" velocity="0.5"/> <!-- force range -->
      <parent link="link${self}"/>
      <child link="thrust${self}"/>
      <origin rpy="0 0 0" xyz="${link_length* 0.5} 0 0"/>
      <axis xyz="0 0 ${rotor_direction}"/>
    </joint>

    <link name="thrust${self}">
      <!-- visual & collisiont -->
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.1" radius="${protector_radius + 0.01}"/>
        </geometry>
      </collision>
    </link>
    <xacro:damping_factor link ="thrust${self}"/>

    <!-- battery: -->
    <!-- use default battery: -->
    <xacro:if value="${with_battery == 1}">
      <xacro:extra_module name = "bat${self}" parent = "link${self}" visible = "1"
                          model_url = "package://hydrus/urdf/mesh/modules/battery/VOLTON-PG-1300LP2-6s.stl" scale="0.001">
        <origin xyz="${link_length/2} 0.0 -0.048" rpy="${pi/2} 0 0"/>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.194"/>
          <inertia
              ixx="0.00005" iyy="0.00012" izz="0.00011"
              ixy="0.0" ixz="0.0" iyz="0.0"/>
        </inertial>
      </xacro:extra_module>
    </xacro:if>

    <!-- leg -->
    <xacro:if value="${with_leg == 1}">
      <!-- head -->
      <xacro:if value="${self == 1}">
        <xacro:standard_leg parent = "link${self}" >
          <origin xyz="${head_leg_offset} 0.0 0" rpy="0 0 0"/>
        </xacro:standard_leg>
      </xacro:if>
      <xacro:unless value="${self == 1}">
        <xacro:standard_leg parent = "link${self}" >
          <origin xyz="${general_leg_offset} 0.0 0" rpy="0 0 0"/>
        </xacro:standard_leg>
        <!-- tail -->
        <xacro:if value="${self == child}">
          <xacro:standard_leg parent = "link${self}" self= "${self + 1}" >
            <origin xyz="${end_leg_offset} 0.0 0" rpy="0 0 0"/>
          </xacro:standard_leg>
        </xacro:if>
      </xacro:unless>
    </xacro:if>

    <!-- joint -->
    <xacro:unless value="${self == child}">
      <joint name="joint${self}" type="revolute">
        <limit effort="10.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
        <parent link="link${self}"/>
        <child link="link${child}"/>
        <origin rpy="0 0 0" xyz="${link_length} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.9" friction="0.05"/>
      </joint>
    </xacro:unless>

    <xacro:if value="${self == 1}">
      <!-- dummy root link for KDL -->
      <link name="root">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="root_joint" type="fixed">
        <parent link="root"/>
        <child link="link${self}"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:if>

    <!-- hardware interface -->
    <xacro:unless value="${self == child}">
      <transmission name="joint_tran${self}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="servo{self}">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:unless>

    <transmission name="rotor_tran${self}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${self}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${self}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <xacro:friction self ="${self}"/>

  </xacro:macro>

</robot>
