<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="tiger_common" >

  <!-- kinematics [m] -->
  <xacro:property name="general_link_length" value="0.523"/>
  <xacro:property name="general_link_radius" value="0.025"/>
  <xacro:property name="center_link_radius" value="0.169"/>
  <xacro:property name="center_link_height" value="0.0928"/>
  <xacro:property name="leg_radius" value="0.01"/>
  <xacro:property name="leg_length" value="0.1005"/>
  <xacro:property name="end_leg_length" value="0.1325"/>

  <!-- dynamics -->
  <xacro:property name="max_force" value="36"/> ### [N]
  <xacro:property name="max_joint_torque" value="6.6"/>  ### [N]

  <baselink name="fc" />
  <thrust_link name="thrust" />
  <m_f_rate value="0" /> <!-- drug torque rate -->

  <xacro:macro name="mesh_model" params="type *origin">
    <visual>
      <xacro:insert_block name="origin"/>
      <geometry>
        <mesh filename="package://tiger/urdf/v1/mesh/${type}.dae"/>
      </geometry>
    </visual>
  </xacro:macro>

  <xacro:macro name="link_collision_model">
    <collision>
      <origin xyz="${general_link_length* 0.5} 0 0" rpy="0 ${pi / 2} 0"/>
      <geometry>
        <cylinder radius="${general_link_radius}" length="${general_link_length}"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="leg_collision_model">
    <collision>
      <origin xyz="0 0 ${leg_length * -0.5}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${leg_radius}" length="${leg_length}"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="end_leg_collision_model">
    <collision>
      <origin xyz="0 0 ${end_leg_length * -0.5}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${leg_radius}" length="${end_leg_length}"/>
      </geometry>
    </collision>
  </xacro:macro>

  <xacro:macro name="extra_module" params="name parent *origin *inertial visible:=0 collision:=0 model_url:=0">
    <joint name="${parent}2${name}" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <xacro:insert_block name="origin" />
    </joint>
    <link name="${name}">
      <xacro:insert_block name="inertial" />
      <xacro:if value="${visible == 1}">
        <visual>
          <geometry>
            <mesh filename="${model_url}"/>
          </geometry>
        </visual>
      </xacro:if>
      <xacro:if value="${collision == 1}">
        <collision>
          <geometry>
            <mesh filename="${model_url}"/>
          </geometry>
        </collision>
      </xacro:if>
    </link>
  </xacro:macro>

  <xacro:macro name="extra_module_with_collision" params="name parent *origin *inertial *collision visible:=0 model_url:=0">
    <joint name="${parent}2${name}" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <xacro:insert_block name="origin" />
    </joint>
    <link name="${name}">
      <xacro:insert_block name="inertial" />
      <xacro:if value="${visible == 1}">
        <visual>
          <geometry>
            <mesh filename="${model_url}"/>
          </geometry>
        </visual>
      </xacro:if>
      <xacro:insert_block name="collision"/>
    </link>
  </xacro:macro>

  <xacro:macro name="joint_transmission" params="joint">
    <transmission name="{joint}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="{joint}_servo">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <!-- friction -->
  <xacro:macro name="friction" params="link">
    <gazebo reference="${link}">
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="damping_factor" params="link">
    <gazebo reference="${link}">
      <dampingFactor>0.00</dampingFactor>
    </gazebo>
  </xacro:macro>
</robot>
