# overwrite parameter for simulation

sensor_plugin:
  mocap:
    ground_truth_sub_name: ground_truth
  gps:
    estimate_mode: 4 #1 << 2
    ned_flag: true # hector_gazebo_plugins/GPS

# ground truth parameter
# global namespace
simulation:
  # gaussian noise
  ground_truth_pos_noise: 0.001
  ground_truth_vel_noise: 0.005
  ground_truth_rot_noise: 0.001
  ground_truth_angular_noise: 0.005

  # drift model: e^(-dt * drift_frequency) * curr_drift + dt * gaussian_kernel(sqrt( 2 * drift_frequency) * drfit))
  # drift diviation:
  ground_truth_vel_drift: 0
  ground_truth_rot_drift: 0
  ground_truth_angular_drift: 0

  # drift frequency:
  ground_truth_vel_drift_frequency: 0
  ground_truth_rot_drift_frequency: 0
  ground_truth_angular_drift_frequency: 0
