<?xml version="1.0"?>
<package format="2">
  <name>aerial_robot_dynamics</name>
  <version>0.0.0</version>
  <description>The aerial_robot_dynamics package</description>

  <maintainer email="sugihara@todo.todo">sugihara</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>benchmark</build_depend>

  <depend>eigen</depend>
  <depend>osqp-eigen</depend>
  <depend>pinocchio</depend>
  <depend>roscpp</depend>
  <depend>urdf</depend>

  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>benchmark</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>xacro</exec_depend>
  <test_depend>rostest</test_depend>

</package>
