@startuml
'https://plantuml.com/class-diagram

set namespaceSeparator ::

abstract class aerial_robot_control::ControlBase {
    + ControlBase()
    + ~ControlBase()
    + initialize()
    + update()
    + activate()
    + reset()
    # template<class T> void getParam()
}

abstract class aerial_robot_control::nmpc::BaseMPC extends aerial_robot_control::ControlBase {
    # mpc_solver_ptr_
    # initPredXU()
    # initMPCSolverPtr()
    # callbackSetRefTraj()
    # rosXU2VecXU()
    # meas2VecX()
    # controlCore()
    # sendCmd()
    # callbackViz()
}

class aerial_robot_control::nmpc::FixQdNMPC extends aerial_robot_control::nmpc::TiltQdServoNMPC {
'x_dim = 13, u_dim = 4, p_dim = 4'
    # initMPCSolverPtr()
    # initAllocMat()
}

'class aerial_robot_control::nmpc::TiltQdNMPC extends aerial_robot_control::nmpc::FixQdNMPC {
''x_dim = 13, u_dim = 8'
'    + TiltQdNMPC()
'    + ~TiltQdNMPC()
'    + initialize()
'    + update()
'    + reset()
'}

class aerial_robot_control::nmpc::TiltQdServoNMPC extends aerial_robot_control::nmpc::BaseMPC {
'x_dim = 17, u_dim = 8, p_dim = 4'
    + TiltQdServoNMPC()
    + ~TiltQdServoNMPC()
    + initialize()
    + update()
    + reset()
    # initMPCSolverPtr()
    # initAllocMat()
    # initParams()
    # initCostW()
    # setControlMode()
    # initJointStates()
    # controlCore()
    # sendCmd()
    # prepareNMPCRef()
    # prepareNMPCParams()
    # callbackViz()
    # callbackJointStates()
    # callbackSetRPY()
    # callbackSetRefXU()
    # callbackSetRefTraj()
    # cfgNMPCCallback()
    # getOdom()
    # getCommand()
    # meas2VecX()
    # printPhysicalParams()
    # setXrUrRef()
    # allocateToXU()
}

class aerial_robot_control::nmpc::TiltQdServoNMPCwITerm extends aerial_robot_control::nmpc::TiltQdServoNMPC {
'x_dim = 17, u_dim = 8， p_dim = 10'
    + initialize()
    # initParams()
    # initMPCSolverPtr()
    # prepareNMPCParams()
    # calcDisturbWrench()
    # callbackViz()
    # cfgNMPCCallback()
}

class aerial_robot_control::nmpc::TiltQdServoNMPCwEKF extends aerial_robot_control::nmpc::TiltQdServoNMPC {
'x_dim = 23, u_dim = 8, p_dim = 4'
unfinished
    + initialize()
    + update()
    + reset()
}

class aerial_robot_control::nmpc::TiltQdServoNMPCwMHE extends aerial_robot_control::nmpc::TiltQdServoNMPCwEKF {
'x_dim = 23, u_dim = 8, p_dim = 4'
unfinished
    + TiltQdServoNMPCwMHE()
    + ~TiltQdServoNMPCwMHE()
    + initialize()
    + update()
    + reset()
}

class aerial_robot_control::nmpc::TiltQdServoThrustNMPCwEKF extends aerial_robot_control::nmpc::TiltQdServoNMPCwEKF {
'x_dim = 27, u_dim = 8, p_dim = 4'
unfinished
    + TiltQdServoThrustNMPCwEKF()
    + ~TiltQdServoThrustNMPCwEKF()
    + initialize()
    + update()
    + reset()
}

class aerial_robot_control::nmpc::TiltTriServoNMPC extends aerial_robot_control::nmpc::TiltQdServoNMPC {
'x_dim = 16, u_dim = 6, p_dim = 4'
    # initMPCSolverPtr()
    # initAllocMat()
}

class aerial_robot_control::nmpc::TiltBiServoNMPC extends aerial_robot_control::nmpc::TiltQdServoNMPC {
'x_dim = 15, u_dim = 4, p_dim = 4'
    # initMPCSolverPtr()
    # initAllocMat()
}

class aerial_robot_control::nmpc::TiltBi2OrdServoNMPC extends aerial_robot_control::nmpc::TiltBiServoNMPC {
'x_dim = 17, u_dim = 4, p_dim = 4'
    # initMPCSolverPtr()
    # initCostW()
    # initJointStates()
    # meas2VecX()
    # callbackJointStates()
    # cfgNMPCCallback()
}

@enduml