ground_controller:
  initial_roll_tilt: 0.8
  torque_compensate_step: 0.001
  
  xy:
    p_gain: 2.5
    i_gain: 0.05
    d_gain: 1.5
    limit_sum: 4.0
    limit_p: 12.0
    limit_i: 12.0
    limit_d: 12.0

  z:
    p_gain: 25.0
    i_gain: 0.5
    d_gain: 2.5
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0
    limit_i: 25.0
    limit_d: 25.0
    force_landing_descending_rate: -0.5

  roll:
    p_gain: 10.0
    i_gain: 0.0
    d_gain: 2.0
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    start_rp_integration_height: 0.01

  pitch:
    p_gain: 5.0
    i_gain: 1.0
    d_gain: 2.0
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    start_rp_integration_height: 0.01

  yaw:
    p_gain: 4.0
    i_gain: 2.0
    d_gain: 8.0
    limit_err_p: 0.4
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    need_d_control: true