<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="dragon_link" >

  <!-- D-H kai description(different from prof.nakamura) -->
  <xacro:macro name="dragon_module" params="self child baselink battery:=1">

    <!-- link without battery -->
    <link name="link${self}">
      <!-- head -->
      <xacro:if value="${self == 1}">
        <inertial>
          <origin xyz="${link_length* 0.5 + 0.0945} -0.0158  -0.0012" rpy="0 0 0"/>
          <mass value="0.3231" />
          <inertia
              ixx="0.0003" iyy="0.0073" izz=" 0.0074"
              ixy="-0.0005" ixz="0.0002" iyz="0.0000"/>
        </inertial>
        <xacro:link_model type="head_link" />
      </xacro:if>
      <xacro:unless value="${self == 1}">

        <!-- end -->
        <xacro:if value="${self == child}">
          <inertial>
            <origin xyz="${link_length* 0.5  -0.0933} 0.0003  0.0136" rpy="0 0 0"/>
            <mass value="0.3543" />
            <inertia
                ixx="0.0003" iyy="0.0078" izz="0.0076"
                ixy="0.0000" ixz="-0.0006" iyz="0.0000"/>
          </inertial>
          <xacro:link_model type="end_link" />
        </xacro:if>
        <xacro:unless value="${self == child}">

          <!-- baselink -->
          <xacro:if value="${baselink}">
            <inertial>
              <origin xyz="${link_length* 0.5 + 0.0255} -0.0086 0.0061" rpy="0 0 0"/>
              <mass value="0.6358" />
              <inertia
                  ixx="0.0007" iyy="0.0195" izz="0.0190"
                  ixy="-0.0009" ixz="-0.0013" iyz="0.0000"/>
            </inertial>
            <xacro:link_model type="base_link" />
          </xacro:if>

          <!-- general -->
          <xacro:unless value="${baselink}">
            <inertial>
              <origin xyz="${link_length* 0.5 - 0.0018} -0.0101 0.0105" rpy="0 0 0"/>
              <mass value="0.5055" />
              <inertia
                  ixx="0.0006" iyy="0.0171" izz="0.0170"
                  ixy="-0.0010" ixz="-0.0010" iyz="0.0001"/>
            </inertial>
            <xacro:link_model type="general_link" />
          </xacro:unless>
        </xacro:unless>
      </xacro:unless>
    </link>
    <xacro:damping_factor link ="link${self}"/>

    <!-- gimbal roll -->
    <joint name="gimbal${self}_roll" type="revolute">
      <limit effort="3" lower="-3.14" upper="3.14" velocity="12.5"/>
      <parent link="link${self}"/>
      <child link="gimbal${self}_roll_module"/>
      <origin rpy="0 0 0" xyz="${link_length/2} 0 0"/>
      <axis xyz="1 0 0"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>

    <link name="gimbal${self}_roll_module">
      <inertial>
        <origin xyz="${gimbal_roll_x_offset -0.0209} 0.0009 0.0265" rpy="0 0 0"/>
        <mass value="0.3337" />
        <inertia
            ixx="0.0004" iyy="0.0005" izz="0.0002"
            ixy="0.0000" ixz="-0.0001" iyz="0.0000"/>
      </inertial>
      <visual>
        <origin xyz="${gimbal_roll_x_offset} 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dragon/urdf/v1_5/mesh/gimbal_roll.stl"/>
        </geometry>
      </visual>

      <!-- cylinder collision geometry works well for FCL -->
      <collision>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0.02"/>
        <geometry>
          <cylinder length="0.3" radius="0.09" />
        </geometry>
      </collision>

    </link>

    <!-- gimbal pitch -->
    <joint name="gimbal${self}_pitch" type="revolute">
      <limit effort="3" lower="-3.14" upper="3.14" velocity="12.5"/>
      <parent link="gimbal${self}_roll_module"/>
      <child link="gimbal${self}_pitch_module"/>
      <origin rpy="0 0 0" xyz="0 0 ${gimbal_pitch_z_offset}"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>

    <link name="gimbal${self}_pitch_module">
      <inertial>
        <origin xyz="0.0000 -0.0001 -0.0010" rpy="0 0 0"/>
        <mass value="0.3455" />
        <inertia
            ixx="0.0047" iyy="0.0003" izz="0.0049"
            ixy="0.0000" ixz="0.0000" iyz="0.0000"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dragon/urdf/v1_5/mesh/gimbal_pitch.stl"/>
        </geometry>
      </visual>
    </link>

    <!-- rotor -->
    <joint name="rotor${self}" type="continuous">
      <limit effort="100.0" lower="${min_force}" upper="${max_force}" velocity="0.5"/>
      <parent link="gimbal${self}_pitch_module"/>
      <child link="thrust${self}"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="thrust${self}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
    </link>

    <!-- special part of duct fun -->
    <joint name="edf${self}_left_mount" type="fixed">
      <child link="edf${self}_left"/>
      <parent link="gimbal${self}_pitch_module"/>
      <origin rpy="0 0 0" xyz="0 0.1115 0 "/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="edf${self}_left">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.00001"/>
        <inertia
            ixx="0.000001" ixy="0.0" ixz="0.0"
            iyy="0.000001" iyz="0.0"
            izz="0.000002"/>
      </inertial>
    </link>
    <joint name="edf${self}_right_mount" type="fixed">
      <child link="edf${self}_right"/>
      <parent link="gimbal${self}_pitch_module"/>
      <origin rpy="0 0 0" xyz="0 -0.1115 0 "/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="edf${self}_right">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.00001"/>
        <inertia
            ixx="0.000001" ixy="0.0" ixz="0.0"
            iyy="0.000001" iyz="0.0"
            izz="0.000002"/>
      </inertial>
    </link>

    <xacro:damping_factor link ="thrust${self}"/>
    <!-- joint -->
    <xacro:unless value="${self == child}">
      <joint name="joint${self}_pitch" type="revolute">
        <limit effort="10.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.1"/>
        <parent link="link${self}"/>
        <child link="inter_joint${self}"/>
        <origin rpy="0 0 0" xyz="${link_length} 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.9" friction="0.05"/>
      </joint>

      <!-- inter joint -->
      <link name="inter_joint${self}">
        <!-- common inertial -->
        <inertial>
          <origin xyz="${inter_joint_x_offset +  0.0028} -0.0044 -0.0008" rpy="0 0 0"/>
          <mass value="0.1219" />
          <inertia
              ixx="0.0001" iyy="0.0001" izz="0.0001"
              ixy="0.0000" ixz="0.0000" iyz="0.0000"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="${inter_joint_x_offset} 0 0"/>
          <geometry>
            <mesh filename="package://dragon/urdf/v1_5/mesh/inter_joint_junction.stl"/>
          </geometry>
        </visual>
      </link>

      <joint name="joint${self}_yaw" type="revolute">
        <limit effort="10.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.1"/>
        <parent link="inter_joint${self}"/>
        <child link="link${child}"/>
        <origin rpy="0 0 0" xyz="${2 * inter_joint_x_offset} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.9" friction="0.05"/>
      </joint>

      <gazebo reference="inter_joint${self}">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
      </gazebo>

    </xacro:unless>

    <xacro:if value="${self == 1}">
      <!-- dummy root link for KDL -->
      <link name="root">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="root_joint" type="fixed">
        <parent link="root"/>
        <child link="link${self}"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:if>

    <!-- set the fcu frame -->
    <xacro:if value="${baselink}">
      <link name="fc">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="fc_joint" type="fixed">
        <child link="fc"/>
        <parent link="link${self}"/>
        <origin rpy="0 0 0" xyz="0.3245 -0.0010 0.0280"/>
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:if>

    <!-- add battery -->
    <xacro:if value="${battery}">
      <xacro:extra_module name="battery${self}" parent="link${self}" visible="1"
                         model_url = "package://dragon/urdf/v1_5/mesh/battery.stl">
        <origin xyz="0.1023 0.0 -0.048" rpy="0 0 0"/>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.446"/>
          <inertia
              ixx="0.0001" iyy="0.0007" izz="0.0007"
              ixy="0.0000" ixz="0.0000"  iyz="0.0000"/>
        </inertial>
      </xacro:extra_module>
    </xacro:if>

    <!-- hardware interface -->
    <xacro:unless value="${self == child}">
      <transmission name="joint${self}_pitch_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}_pitch">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_servo{self}_pitch">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
      <transmission name="joint${self}_yaw_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}_yaw">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_servo{self}_yaw">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:unless>

    <transmission name="gimbal${self}_roll_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gimbal${self}_roll">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gimbal_servo{self}_roll">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="gimbal${self}_pitch_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gimbal${self}_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gimbal_servo{self}_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="rotor${self}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${self}">
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${self}">
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      </transmission>
    <xacro:friction self ="${self}"/>

  </xacro:macro>

</robot>
