#[rad/s^2]
float32 roll_pitch_p
float32 roll_pitch_i
float32 roll_pitch_d
float32 yaw_d
float32 roll_pitch_limit
float32 roll_pitch_p_limit
float32 roll_pitch_i_limit
float32 roll_pitch_d_limit
float32 yaw_d_limit
---
bool success
