/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of:
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
#define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
#define _CASADI_NAMESPACE_CONCAT(NS, ID) NS##ID
#define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
#define CASADI_PREFIX(ID) qd_full_model_expl_vde_adj_##ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define CASADI_SYMBOL_EXPORT
#else
#define CASADI_SYMBOL_EXPORT __declspec(dllexport)
#endif
#elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define CASADI_SYMBOL_EXPORT __attribute__((visibility("default")))
#else
#define CASADI_SYMBOL_EXPORT
#endif
#endif

casadi_real casadi_sq(casadi_real x)
{
  return x * x;
}

static const casadi_int casadi_s0[17] = { 13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static const casadi_int casadi_s1[8] = { 4, 1, 0, 4, 0, 1, 2, 3 };
static const casadi_int casadi_s2[21] = { 17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 };

/* qd_full_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[4])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem)
{
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28,
      a3, a4, a5, a6, a7, a8, a9;
  a0 = 0.;
  if (res[0] != 0)
    res[0][0] = a0;
  if (res[0] != 0)
    res[0][1] = a0;
  if (res[0] != 0)
    res[0][2] = a0;
  a0 = arg[1] ? arg[1][0] : 0;
  if (res[0] != 0)
    res[0][3] = a0;
  a0 = arg[1] ? arg[1][1] : 0;
  if (res[0] != 0)
    res[0][4] = a0;
  a0 = arg[1] ? arg[1][2] : 0;
  if (res[0] != 0)
    res[0][5] = a0;
  a0 = arg[0] ? arg[0][12] : 0;
  a1 = 5.0000000000000000e-01;
  a2 = arg[1] ? arg[1][9] : 0;
  a2 = (a1 * a2);
  a3 = (a0 * a2);
  a4 = arg[0] ? arg[0][11] : 0;
  a5 = arg[1] ? arg[1][8] : 0;
  a5 = (a1 * a5);
  a6 = (a4 * a5);
  a3 = (a3 + a6);
  a6 = arg[0] ? arg[0][10] : 0;
  a7 = arg[1] ? arg[1][7] : 0;
  a7 = (a1 * a7);
  a8 = (a6 * a7);
  a3 = (a3 + a8);
  a8 = 2.;
  a9 = arg[0] ? arg[0][7] : 0;
  a10 = arg[2] ? arg[2][0] : 0;
  a11 = arg[2] ? arg[2][1] : 0;
  a10 = (a10 + a11);
  a11 = arg[2] ? arg[2][2] : 0;
  a10 = (a10 + a11);
  a11 = arg[2] ? arg[2][3] : 0;
  a10 = (a10 + a11);
  a11 = 9.4661113214691406e-01;
  a12 = arg[1] ? arg[1][4] : 0;
  a12 = (a11 * a12);
  a13 = (a10 * a12);
  a14 = (a9 * a13);
  a14 = (a8 * a14);
  a3 = (a3 - a14);
  a14 = arg[0] ? arg[0][8] : 0;
  a15 = arg[1] ? arg[1][3] : 0;
  a15 = (a11 * a15);
  a16 = (a10 * a15);
  a17 = (a14 * a16);
  a17 = (a8 * a17);
  a3 = (a3 + a17);
  if (res[0] != 0)
    res[0][6] = a3;
  a3 = (a4 * a2);
  a17 = (a0 * a5);
  a3 = (a3 - a17);
  a17 = arg[1] ? arg[1][6] : 0;
  a1 = (a1 * a17);
  a17 = (a6 * a1);
  a3 = (a3 - a17);
  a17 = (a9 + a9);
  a18 = arg[1] ? arg[1][5] : 0;
  a11 = (a11 * a18);
  a10 = (a10 * a11);
  a18 = (a8 * a10);
  a17 = (a17 * a18);
  a3 = (a3 - a17);
  a17 = arg[0] ? arg[0][6] : 0;
  a18 = (a8 * a17);
  a19 = (a18 * a13);
  a3 = (a3 - a19);
  a19 = arg[0] ? arg[0][9] : 0;
  a20 = (a19 * a16);
  a20 = (a8 * a20);
  a3 = (a3 + a20);
  if (res[0] != 0)
    res[0][7] = a3;
  a3 = (a0 * a7);
  a20 = (a6 * a2);
  a3 = (a3 - a20);
  a20 = (a4 * a1);
  a3 = (a3 - a20);
  a20 = (a14 + a14);
  a10 = (a8 * a10);
  a20 = (a20 * a10);
  a3 = (a3 - a20);
  a20 = (a19 * a13);
  a20 = (a8 * a20);
  a3 = (a3 + a20);
  a20 = (a8 * a17);
  a10 = (a20 * a16);
  a3 = (a3 + a10);
  if (res[0] != 0)
    res[0][8] = a3;
  a3 = (a6 * a5);
  a10 = (a4 * a7);
  a3 = (a3 - a10);
  a10 = (a0 * a1);
  a3 = (a3 - a10);
  a10 = (a8 * a14);
  a13 = (a10 * a13);
  a3 = (a3 + a13);
  a13 = (a8 * a9);
  a16 = (a13 * a16);
  a3 = (a3 + a16);
  if (res[0] != 0)
    res[0][9] = a3;
  a3 = 9.7911700000000001e-03;
  a16 = (a3 * a0);
  a21 = 1.1532655290086645e+02;
  a22 = arg[1] ? arg[1][11] : 0;
  a21 = (a21 * a22);
  a22 = (a16 * a21);
  a23 = 8.6710299999999997e-03;
  a24 = (a23 * a4);
  a25 = 1.0213284009980421e+02;
  a26 = arg[1] ? arg[1][12] : 0;
  a25 = (a25 * a26);
  a26 = (a24 * a25);
  a22 = (a22 - a26);
  a26 = 8.6703200000000005e-03;
  a27 = (a4 * a25);
  a28 = (a0 * a21);
  a27 = (a27 - a28);
  a27 = (a26 * a27);
  a22 = (a22 + a27);
  a27 = (a14 * a2);
  a22 = (a22 - a27);
  a27 = (a19 * a5);
  a22 = (a22 + a27);
  a27 = (a17 * a7);
  a22 = (a22 + a27);
  a27 = (a9 * a1);
  a22 = (a22 - a27);
  if (res[0] != 0)
    res[0][10] = a22;
  a26 = (a26 * a6);
  a22 = (a26 * a25);
  a27 = 1.1533599682595336e+02;
  a28 = arg[1] ? arg[1][10] : 0;
  a27 = (a27 * a28);
  a0 = (a0 * a27);
  a28 = (a6 * a25);
  a0 = (a0 - a28);
  a23 = (a23 * a0);
  a22 = (a22 + a23);
  a16 = (a16 * a27);
  a22 = (a22 - a16);
  a16 = (a9 * a2);
  a22 = (a22 + a16);
  a16 = (a17 * a5);
  a22 = (a22 + a16);
  a16 = (a19 * a7);
  a22 = (a22 - a16);
  a16 = (a14 * a1);
  a22 = (a22 - a16);
  if (res[0] != 0)
    res[0][11] = a22;
  a24 = (a24 * a27);
  a26 = (a26 * a21);
  a24 = (a24 - a26);
  a6 = (a6 * a21);
  a4 = (a4 * a27);
  a6 = (a6 - a4);
  a3 = (a3 * a6);
  a24 = (a24 + a3);
  a17 = (a17 * a2);
  a24 = (a24 + a17);
  a5 = (a9 * a5);
  a24 = (a24 - a5);
  a7 = (a14 * a7);
  a24 = (a24 + a7);
  a1 = (a19 * a1);
  a24 = (a24 - a1);
  if (res[0] != 0)
    res[0][12] = a24;
  a24 = 1.0999999999999999e-02;
  a1 = (a24 * a25);
  a7 = -8.6575200000000005e-02;
  a5 = (a7 * a21);
  a1 = (a1 - a5);
  a5 = -8.5000000000000006e-02;
  a17 = (a5 * a27);
  a1 = (a1 + a17);
  a17 = 1.;
  a2 = casadi_sq(a9);
  a2 = (a8 * a2);
  a17 = (a17 - a2);
  a2 = casadi_sq(a14);
  a8 = (a8 * a2);
  a17 = (a17 - a8);
  a17 = (a17 * a11);
  a10 = (a10 * a19);
  a18 = (a18 * a9);
  a10 = (a10 - a18);
  a10 = (a10 * a12);
  a17 = (a17 + a10);
  a13 = (a13 * a19);
  a20 = (a20 * a14);
  a13 = (a13 + a20);
  a13 = (a13 * a15);
  a17 = (a17 + a13);
  a1 = (a1 + a17);
  if (res[0] != 0)
    res[0][13] = a1;
  a5 = (a5 * a27);
  a1 = (a24 * a25);
  a13 = 8.3424799999999993e-02;
  a15 = (a13 * a21);
  a1 = (a1 + a15);
  a5 = (a5 - a1);
  a5 = (a5 + a17);
  if (res[0] != 0)
    res[0][14] = a5;
  a5 = (a24 * a25);
  a13 = (a13 * a21);
  a5 = (a5 - a13);
  a13 = 8.5000000000000006e-02;
  a1 = (a13 * a27);
  a5 = (a5 + a1);
  a5 = (a5 + a17);
  if (res[0] != 0)
    res[0][15] = a5;
  a13 = (a13 * a27);
  a24 = (a24 * a25);
  a7 = (a7 * a21);
  a24 = (a24 + a7);
  a13 = (a13 - a24);
  a13 = (a13 + a17);
  if (res[0] != 0)
    res[0][16] = a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int qd_full_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw,
                                                    casadi_real* w, int mem)
{
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int qd_full_model_expl_vde_adj_alloc_mem(void)
{
  return 0;
}

CASADI_SYMBOL_EXPORT int qd_full_model_expl_vde_adj_init_mem(int mem)
{
  return 0;
}

CASADI_SYMBOL_EXPORT void qd_full_model_expl_vde_adj_free_mem(int mem)
{
}

CASADI_SYMBOL_EXPORT int qd_full_model_expl_vde_adj_checkout(void)
{
  return 0;
}

CASADI_SYMBOL_EXPORT void qd_full_model_expl_vde_adj_release(int mem)
{
}

CASADI_SYMBOL_EXPORT void qd_full_model_expl_vde_adj_incref(void)
{
}

CASADI_SYMBOL_EXPORT void qd_full_model_expl_vde_adj_decref(void)
{
}

CASADI_SYMBOL_EXPORT casadi_int qd_full_model_expl_vde_adj_n_in(void)
{
  return 4;
}

CASADI_SYMBOL_EXPORT casadi_int qd_full_model_expl_vde_adj_n_out(void)
{
  return 1;
}

CASADI_SYMBOL_EXPORT casadi_real qd_full_model_expl_vde_adj_default_in(casadi_int i)
{
  switch (i)
  {
    default:
      return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* qd_full_model_expl_vde_adj_name_in(casadi_int i)
{
  switch (i)
  {
    case 0:
      return "i0";
    case 1:
      return "i1";
    case 2:
      return "i2";
    case 3:
      return "i3";
    default:
      return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* qd_full_model_expl_vde_adj_name_out(casadi_int i)
{
  switch (i)
  {
    case 0:
      return "o0";
    default:
      return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* qd_full_model_expl_vde_adj_sparsity_in(casadi_int i)
{
  switch (i)
  {
    case 0:
      return casadi_s0;
    case 1:
      return casadi_s0;
    case 2:
      return casadi_s1;
    case 3:
      return casadi_s1;
    default:
      return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* qd_full_model_expl_vde_adj_sparsity_out(casadi_int i)
{
  switch (i)
  {
    case 0:
      return casadi_s2;
    default:
      return 0;
  }
}

CASADI_SYMBOL_EXPORT int qd_full_model_expl_vde_adj_work(casadi_int* sz_arg, casadi_int* sz_res, casadi_int* sz_iw,
                                                         casadi_int* sz_w)
{
  if (sz_arg)
    *sz_arg = 4;
  if (sz_res)
    *sz_res = 1;
  if (sz_iw)
    *sz_iw = 0;
  if (sz_w)
    *sz_w = 0;
  return 0;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
