//
// Created by jinjie on 24/07/31.
//

#ifndef TILT_QD_SERVO_THRUST_DIST_NMPC_CONTROLLER_H
#define TILT_QD_SERVO_THRUST_DIST_NMPC_CONTROLLER_H

#include "nmpc_solver.h"

#endif  // TILT_QD_SERVO_THRUST_DIST_NMPC_CONTROLLER_H
