//
// Created by li-jinjie on 23-11-25.
//

#ifndef AERIAL_ROBOT_CONTROL_BASE_MPC_CONTROLLER_H
#define AERIAL_ROBOT_CONTROL_BASE_MPC_CONTROLLER_H

#endif  // AERIAL_ROBOT_CONTROL_BASE_MPC_CONTROLLER_H
