servo_controller:
  gimbals:
    angle_sgn: -1
    angle_scale: 0.00058904862
    zero_point_offset: 7500

    controller1:
      id: 0
      name: gimbal1
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller2:
      id: 1
      name: gimbal2
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController
