sensor_plugin:
  vo:
    vo_sub_topic_name: Odometry_precede
    level_pos_noise_sigma: 0.01  # 0.01 is better that 0.001
    z_pos_noise_sigma: 0.01 # 0.01 is better than 0.001
    z_vel_mode: false
    vel_noise_sigma: 0.01 # TODO: modification
    sensor_frame: lidar_imu
    reference_frame: fc
    vio_mode: true
    local_vel_mode: false # the twist/twist/velocity is described in global frame
    time_sync: false
    reset_duration: 0.5

    fusion_mode: 2 # ONLY_POS_MODE = 0, ONLY_VEL_MODE = 1, POS_VEL_MODE = 2
    #param_verbose: true
