# control
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

attitude_controller:
  type: flight_controllers/SimulationAttitudeController


# sensor -> aerial_robot_hw_sim
## mocap
simulation:
  mocap_pub_rate: 0.01
  mocap_pos_noise: 0.001
  mocap_rot_noise: 0.001

  # ground truth -> aerial_robot_hw_sim
  ground_truth_pub_rate: 0.01
