<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_link2" >

  <xacro:macro name="link2">

    <!-- fc frame -->
    <link name="fc">
      <xacro:virtual_inertial/>
    </link>
    <joint name="fc_joint" type="fixed">
      <child link="fc" />
      <parent link="link2" />
      <origin xyz="0.0864 -0.0012 0.020" rpy="0 0 0" />
      <axis xyz="0 0 1"/>
    </joint>

    <link name="link2">
      <inertial>
        <origin xyz="0.29247546 -0.04173228 0.00214003" rpy="0 0 0"/>
        <mass value="1.21919627"/>
        <inertia
             ixx="0.00538607" iyy="0.04105715" izz="0.04397541"
            ixy="-0.00237976" ixz="0.00218016" iyz="0.00011267" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://delta/urdf/mesh/20240319_mesh/link2_base.dae" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://delta/urdf/mesh/20240319_mesh/link2_base_opt.stl" />
        </geometry>
      </collision>
    </link>
    <xacro:large_friction link="link2"/>

    <!-- leg -->
    <link name="link2_leg">
      <inertial>
        <mass value="${leg_mass}"/>
        <inertia
            ixx="${(leg_radius * leg_radius / 4.0 + leg_length * leg_length / 12.0) * leg_mass}" ixy="0.0" ixz="0.0"
            iyy="${(leg_radius * leg_radius / 4.0 + leg_length * leg_length / 12.0) * leg_mass}" iyz="0.0"
            izz="${(leg_radius * leg_radius / 2.0) * leg_mass}"/>
      </inertial>
      <collision>
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}"/>
        </geometry>
      </collision>
    </link>
    <joint name="link2_leg_joint" type="fixed">
      <parent link="link2"/>
      <child link="link2_leg"/>
      <origin rpy="0 0 0" xyz="0.056 0 ${-0.012-leg_length/2.0}"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="gimbal_link2">
      <inertial>
        <origin xyz="0.01205240 -0.00000221 0.01260343" rpy="0 0 0"/>
        <mass value="0.27751558"/>
        <inertia
            ixx="0.00068946"  iyy="0.00075023" izz="0.00016497"
            ixy="0.00000004" ixz="-0.00015101" iyz="0.00000005"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://delta/urdf/mesh/20240319_mesh/link2_gimbal.dae" />
        </geometry>
      </visual>
    </link>

    <link name="link2_center">
      <xacro:virtual_inertial/>
    </link>
    <joint name="link2_center_joint" type="fixed">
      <parent link="link2"/>
      <child link="link2_center"/>
      <origin xyz="0.26375 0.15228 0" rpy="0 0 ${pi}"/>
    </joint>

  </xacro:macro>
</robot>
