<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="brick" >

  <xacro:property name="brick_x" value="0.5"/>
  <xacro:property name="brick_y" value="0.3"/>
  <xacro:property name="brick_z" value="0.2"/>
  <xacro:property name="mass" value="0.4"/>

  <link name="brick">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${1 / 3 * (brick_y * brick_y + brick_z * brick_z) * mass}" ixy="0.0" ixz="0.0"
          iyy="${1 / 3 * (brick_z * brick_z + brick_x * brick_x) * mass}" iyz="0.0"
          izz="${1 / 3 * (brick_x * brick_x + brick_y * brick_y) * mass}"/>
    </inertial>
    <collision>
      <!-- <origin xyz="${brick_x / 2} ${brick_y / 2} ${brick_z / 2}"/> -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${brick_x} ${brick_y} ${brick_z}"/>
      </geometry>
    </collision>
    <visual>
      <!-- <origin xyz="${brick_x / 2} ${brick_y / 2} ${brick_z / 2}"/> -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${brick_x} ${brick_y} ${brick_z}"/>
      </geometry>
    </visual>
  </link>
  <gazebo reference="brick">
    <mu1 value="0.8"/>
    <mu2 value="0.8"/>
  </gazebo>
</robot>
