<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="dragon_link" >

  <!-- D-H kai description(different from prof.nakamura) -->
  <xacro:macro name="dragon_module" params="self child baselink">

    <!-- link -->
    <link name="link${self}">
      <!-- head -->
      <xacro:if value="${self == 1}">
        <inertial>
          <origin xyz="${link_length* 0.5 + 20.63 * 0.001} ${-7.10 * 0.001} ${-24.66 * 0.001}" rpy="0 0 0"/>
          <mass value="0.7485" />
          <!-- bad problem: https://github.com/tongtybj/aerial_robot/issues/155
          <inertia
              ixx="0.0014" iyy="0.0154" izz="0.0147"
              ixy="-0.0008" ixz="0.0006" iyz="0.0"/> -->
          <inertia
              ixx="0.0009" iyy="0.0146" izz="0.0143"
              ixy="-0.0009" ixz="0.0002" iyz="0.0001"/>
        </inertial>
        <xacro:link_model type="head_link" />
      </xacro:if>
      <xacro:unless value="${self == 1}">

        <!-- tail -->
        <xacro:if value="${self == child}">
          <inertial>
            <origin xyz="${link_length* 0.5 - 47.26 * 0.001} ${-0.12 * 0.001} ${-17.74 * 0.001}" rpy="0 0 0"/>
            <mass value="0.7460" />
            <!-- bad problem: https://github.com/tongtybj/aerial_robot/issues/155
            <inertia
                ixx="0.0014" iyy="0.0158" izz="0.0145"
                ixy="0.0" ixz="-0.0006" iyz="0.0"/> -->
            <inertia
                ixx="0.0012" iyy="0.0139" izz="0.0128"
                ixy="0.0" ixz="0.0" iyz="0.0"/>
          </inertial>
          <xacro:link_model type="end_link" />
        </xacro:if>
        <xacro:unless value="${self == child}">
          <!-- baselink -->
          <xacro:if value="${baselink}">
            <inertial>
              <origin xyz="${link_length* 0.5 + 11.73 * 0.001} ${-4.91 * 0.001} ${-13.87 * 0.001}" rpy="0 0 0"/>
              <mass value="1.096" />
              <!-- bad problem: https://github.com/tongtybj/aerial_robot/issues/155
              <inertia
                  ixx="0.0019" iyy="0.0226" izz="0.0217"
                  ixy="-0.0009" ixz="-0.0007" iyz="0.0"/> -->
              <inertia
                  ixx="0.0017" iyy="0.0223" izz="0.0216"
                  ixy="-0.0009" ixz="-0.0009" iyz="0.0001"/>
            </inertial>
            <xacro:link_model type="baselink" />
          </xacro:if>
          <!-- general -->
          <xacro:unless value="${baselink}">
            <inertial>
              <origin xyz="${link_length* 0.5 - 11.42 * 0.001} ${-6.06 * 0.001} ${-14.09 * 0.001}" rpy="0 0 0"/>
              <mass value="0.8890" />
              <!-- bad problem: https://github.com/tongtybj/aerial_robot/issues/155
              <inertia
                  ixx="0.0017" iyy="0.02" izz="0.019"
                  ixy="-0.0009" ixz="-0.0004" iyz="0.0"/> -->
              <inertia
                  ixx="0.0013" iyy="0.0194" izz="0.0188"
                  ixy="-0.0008" ixz="0.0007" iyz="0.0"/>
            </inertial>
            <xacro:link_model type="general_link" />
          </xacro:unless>
        </xacro:unless>
      </xacro:unless>
    </link>
    <xacro:damping_factor link ="link${self}"/>

    <!-- gimbal roll -->
    <joint name="gimbal${self}_roll" type="revolute">
      <limit effort="3" lower="-3.14" upper="3.14" velocity="12.5"/>
      <parent link="link${self}"/>
      <child link="gimbal${self}_roll_module"/>
      <origin rpy="0 0 0" xyz="${link_length/2} 0 0"/>
      <axis xyz="1 0 0"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>

    <link name="gimbal${self}_roll_module">
      <inertial>
        <origin xyz="${gimbal_roll_x_offset - 17.46431 * 0.001} ${0.42738 * 0.001} ${15.47344 * 0.001}" rpy="0 0 0"/>
        <mass value="0.45058" />
        <!-- bad problem: https://github.com/tongtybj/aerial_robot/issues/155
        <inertia
            ixx="0.0005" iyy="0.0007" izz="0.0004"
            ixy="0" ixz="-0.0002" iyz="0.0"/>
        -->
        <inertia
            ixx="0.0004" iyy="0.0005" izz="0.0003"
            ixy="0" ixz="-0.0003" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="${gimbal_roll_x_offset} 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dragon/urdf/mesh/ducted_fan_gimbal_roll.dae"/>
        </geometry>
      </visual>

      <!-- box collision not work good for FCL
      <collision>
        <origin rpy="0 0 0" xyz="${gimbal_roll_x_offset}  0 0"/>
        <geometry>
          <box size="0.1 0.3 0.1686"/>
        </geometry>
      </collision>
      -->
      <!-- cylinder collision geometry works well for FCL -->
      <collision>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0.02"/>
        <geometry>
          <cylinder length="0.3" radius="0.09" />
        </geometry>
      </collision>

    </link>

    <!-- gimbal pitch -->
    <joint name="gimbal${self}_pitch" type="revolute">
      <limit effort="3" lower="-3.14" upper="3.14" velocity="12.5"/>
      <parent link="gimbal${self}_roll_module"/>
      <child link="gimbal${self}_pitch_module"/>
      <origin rpy="0 0 0" xyz="0 0 ${gimbal_pitch_z_offset}"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.0"/>
    </joint>

    <link name="gimbal${self}_pitch_module">
      <inertial>
        <origin xyz="0 ${0.47 * 0.001}  ${-7.38 * 0.001}" rpy="0 0 0"/>
        <mass value=".4187" />
        <inertia
            ixx="0.0047" iyy="0.0002" izz="0.0047"
            ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://dragon/urdf/mesh/ducted_fan_gimbal_pitch.dae"/>
        </geometry>
      </visual>
    </link>

    <!-- rotor -->
    <joint name="rotor${self}" type="continuous">
      <limit effort="100.0" lower="0" upper="${max_force}" velocity="0.5"/>
      <parent link="gimbal${self}_pitch_module"/>
      <child link="thrust${self}"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="thrust${self}">
      <inertial>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
        <mass value="0.0001"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
    </link>

    <!-- special part of duct fun -->
    <joint name="edf${self}_left_mount" type="fixed">
      <child link="edf${self}_left"/>
      <parent link="gimbal${self}_pitch_module"/>
      <origin rpy="0 0 0" xyz="0 0.1115 0 "/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="edf${self}_left">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.00001"/>
        <inertia
            ixx="0.000001" ixy="0.0" ixz="0.0"
            iyy="0.000001" iyz="0.0"
            izz="0.000002"/>
      </inertial>
    </link>
    <joint name="edf${self}_right_mount" type="fixed">
      <child link="edf${self}_right"/>
      <parent link="gimbal${self}_pitch_module"/>
      <origin rpy="0 0 0" xyz="0 -0.1115 0 "/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="edf${self}_right">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.00001"/>
        <inertia
            ixx="0.000001" ixy="0.0" ixz="0.0"
            iyy="0.000001" iyz="0.0"
            izz="0.000002"/>
      </inertial>
    </link>

    <xacro:damping_factor link ="thrust${self}"/>
    <!-- joint -->
    <xacro:unless value="${self == child}">
      <joint name="joint${self}_pitch" type="revolute">
        <limit effort="10.0" lower="-1.57" upper="1.57" velocity="0.1"/>
        <parent link="link${self}"/>
        <child link="inter_joint${self}"/>
        <origin rpy="0 0 0" xyz="${link_length} 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.9" friction="0.05"/>
      </joint>

      <!-- inter joint -->
      <link name="inter_joint${self}">
        <!-- common inertial -->
        <inertial>
          <origin xyz="${inter_joint_x_offset + 3.43 * 0.001} ${-4.27 * 0.001} ${-1.55 * 0.001}" rpy="0 0 0"/>
          <mass value="0.1329" />
          <inertia
              ixx="0.0001" iyy="0.0001" izz="0.0001"
              ixy="0" ixz="0.0" iyz="0.0"/>
        </inertial>
        <visual>
          <origin rpy="0 0 0" xyz="${inter_joint_x_offset} 0 0"/>
          <geometry>
            <mesh filename="package://dragon/urdf/mesh/inter_joint_junction.dae"/>
          </geometry>
        </visual>
      </link>

      <joint name="joint${self}_yaw" type="revolute">
        <limit effort="10.0" lower="-1.57" upper="1.57" velocity="0.1"/>
        <parent link="inter_joint${self}"/>
        <child link="link${child}"/>
        <origin rpy="0 0 0" xyz="${2 * inter_joint_x_offset} 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.9" friction="0.05"/>
      </joint>

      <gazebo reference="inter_joint${self}">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
      </gazebo>

    </xacro:unless>

    <xacro:if value="${self == 1}">
      <!-- dummy root link for KDL -->
      <link name="root">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="root_joint" type="fixed">
        <parent link="root"/>
        <child link="link${self}"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:if>

    <!-- set the fcu frame -->
    <xacro:if value="${baselink}">
      <link name="fc">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="0.00001"/>
          <inertia
              ixx="0.000001" ixy="0.0" ixz="0.0"
              iyy="0.000001" iyz="0.0"
              izz="0.000002"/>
        </inertial>
      </link>
      <joint name="fc_joint" type="fixed">
        <child link="fc"/>
        <parent link="link${self}"/>
        <origin rpy="0 0 0" xyz="0.316 -0.004 0.043"/>
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:if>

    <!-- hardware interface -->
    <xacro:unless value="${self == child}">
      <transmission name="joint${self}_pitch_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}_pitch">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_servo{self}_pitch">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
      <transmission name="joint${self}_yaw_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint${self}_yaw">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint_servo{self}_yaw">
          <!-- TODO: effort is torque, maybe position is enough -->
          <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </xacro:unless>

    <transmission name="gimbal${self}_roll_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gimbal${self}_roll">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gimbal_servo{self}_roll">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="gimbal${self}_pitch_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="gimbal${self}_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="gimbal_servo{self}_pitch">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="rotor${self}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${self}">
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${self}">
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      </transmission>
    <xacro:friction self ="${self}"/>

  </xacro:macro>

</robot>
