# Teleop Basic Param

navigation:
  xy_control_mode: 0
  # World Pos Control Mode: 0
  # World Vel Control Mode: 2
  # Local Vel Control Mode: 3
  # Attitude Control Mode: 4

  takeoff_height: 1.0
  outdoor_takeoff_height: 1.0

  joy_udp: false
  max_target_vel: 0.5
  joy_target_vel_interval: 0.005  # 0.2 / 20 = 0.01, 0.005 ~ 0.01  m/s
  joy_target_z_interval: 0.005
  max_target_yaw_rate: 0.1 #  0.05
  cmd_vel_lev2_gain : 2.0

  gain_tunning_mode: 0
  max_target_tilt_angle: 0.2
  cmd_angle_lev2_gain : 1.5

  # gps waypoint
  gps_waypoint_threshold: 3.0
  gps_waypoint_check_du: 1.0

  # force landing
  force_landing_auto_stop_flag: false

  # desire tilt
  baselink_rot_pub_interval: 0.2
  baselink_rot_change_thresh: 0.04 # 0.2 hz -> 0.04; 0.01 hz-> 0.02

  # trajectory
  trajectory_min_du: 2.0
  trajectory_mean_yaw_rate: 0.6
  enable_latch_yaw_trajectory: false
