controller:
  baselink: fc
  only_three_axis_mode: true
  verbose: true
  real_machine: false
  control_verbose: false

  # alt [N]
  alt:
    offset: 0
    limit: 28
    p_term_limit: 28
    i_term_limit: 28
    d_term_limit: 28
    alt_landing_const_i_ctrl_thresh: -0.3

  # xy [rad]
  xy:
    p_gain: 2.5 # 10 / 7.38: sucess in real machine, but weak; divided by mass
    i_gain: 0.03 # divided by mass
    hovering_i_gain: 0.03 # divided by mass
    d_gain: 4 # 40.0 / 7.38 # 20 / 7.38: sucess in real machine, but weak; divided by mass
    limit: 100 # divided by mass
    p_term_limit: 10 # [m/s^2] divided by mass
    i_term_limit: 10 # [m/s^2] divided by mass
    d_term_limit: 10 # [m/s^2] divided by mass
    x_offset: 0
    y_offset: 0

  # yaw [N]
  yaw:
    limit: 10.0
    p_term_limit: 10.0
    i_term_limit: 10.0
    d_term_limit: 10.0
    p_gain: -10 # should be negative
    i_gain: 0.1
    d_gain: -5 # should be negative

  # pitch & roll
  pitch_roll:
    control_p_det_thresh: 0.00025
    control_rate_thresh: 0.7
    limit: 20.0
    p_term_limit: 20.0
    i_term_limit: 20.0
    d_term_limit: 20.0
    p_gain: 20
    i_gain: 2.0
    d_gain: 0.5 #pitch big noise from gyro

  # desire tilt
  tilt_pub_interval: 0.2

  # gimbal vectoring function check
  gimbal_vectoring_check_flag: false
