<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrusx_common" >

  <xacro:property name="pi" value="3.1415926535897931" />
  <!-- kinematics [m] -->
  <xacro:property name="link_length" value=".6" />
  <xacro:property name="link_rod_length" value=".528" />
  <xacro:property name="protector_radius" value=".1925" />
  <xacro:property name="link_joint_offset" value="0.3" />
  <xacro:property name="rotor_radius" value=".02" />
  <xacro:property name="rotor_height" value=".05" />
  <xacro:property name="bat_offset" value="0.0" />
  <xacro:property name="pc_c_offset" value="0.22" />  <!-- odroid u4: 0.22, euclid: 0 -->
  <xacro:property name="pc_v_offset" value="0.2" />  <!-- odroid u4: -0.2, euclid: 0.2 -->
  <xacro:property name="pcs_cable_offset" value="0.0" />
  <xacro:property name="fc_offset" value="-0.26" />
  <xacro:property name="sensor_c_offset" value="-0.215" />
  <xacro:property name="sensor_v_offset" value="-0.01" />
  <xacro:property name="head_leg_offset" value="-0.25" />
  <xacro:property name="tail_leg_offset" value="0.235" />

  <!-- inertial paramters -->
  <!-- mass [Kg] -->
  <xacro:property name="link_rod_mass" value="0.099" />
  <xacro:property name="link_center_mass" value=".211" />
  <xacro:property name="joint_mass" value=".19" /> <!-- rollor: 0.15 -->
  <xacro:property name="protector_mass" value=".05" />
  <xacro:property name="protector_holder_mass" value=".0386" />
  <xacro:property name="bat_mass" value="0.193" /> <!-- hyperon: 0.41, white(2700mAh): 0.364, white(1300mAh): 0.193 -->
  <xacro:property name="fc_mass" value=".03" />
  <xacro:property name="pc_c_mass" value=".14" /> <!-- odoroid u4: 0.1, euclid: 0.13 -->
  <xacro:property name="pc_v_mass" value=".24" />
  <xacro:property name="pcs_cable_mass" value=".03" />
  <xacro:property name="head_leg_mass" value="0.045" /> <!-- rollor: 0.017 -->
  <xacro:property name="tail_leg_mass" value="0.073" /> <!-- rollor: 0.017 -->
  <xacro:property name="sensor_c_mass" value="0.03" /> <!-- gps: 0.43 -->
  <xacro:property name="sensor_v_mass" value="0.18" />
  <xacro:property name="rotor_mass" value=".05" /> <!-- exclude from center mass -->

  <!-- inertial [N*m*m] -->
  <xacro:property name="link_rod_inertia" value="${link_rod_mass * link_rod_length * link_rod_length /12}" /> <!-- mass * dist * dist -->
  <xacro:property name="protector_inertia" value="${protector_mass * protector_radius * protector_radius}" /> <!-- mass * dist * dist -->
  <xacro:property name="protector_holder_inertia" value="${protector_holder_mass * protector_radius * protector_radius}" /> <!-- mass * dist * dist -->

  <!-- dynamics -->
  <xacro:property name="max_force" value="18" /> <!-- [N] -->

  <xacro:macro name="link_model" params="type">
    <!-- for fcl in planning -->
    <collision>
      <origin rpy="0 0 0" xyz="${link_length* 0.5} 0 -0.03"/>
      <geometry>
        <box size="${link_length} 0.05 0.15"/>
      </geometry>
    </collision>

    <visual>
      <origin rpy="${-pi/2} 0 0" xyz="${link_length* 0.5} 0 0"/>
      <geometry>
        <mesh filename="package://hydrus/urdf/hydrusx/mesh/hydrusx_link${type}.dae"/>
      </geometry>
    </visual>
  </xacro:macro>

  <xacro:macro name="extra_module" params="name parent mass offset">
    <joint name="link2${name}" type="fixed">
      <parent link="link${parent}"/>
      <child link="${name}"/>
      <origin rpy="0 0 0" xyz="${offset} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
            ixx="0.00001" ixy="0.0" ixz="0.0"
            iyy="0.00001" iyz="0.0"
            izz="0.00002"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- friction -->
  <xacro:macro name="friction" params="self">
    <gazebo reference="link${self}">
      <mu1>0.3</mu1>
      <mu2>0.3</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="damping_factor" params="link">
    <gazebo reference="${link}">
      <dampingFactor>0.00</dampingFactor>
    </gazebo>
  </xacro:macro>
</robot>
