aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_adaptive_controller

controller:
  xy:
    p_gain: 2.3
    i_gain: 0.02
    d_gain: 4.0
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 3.6
    i_gain: 1.55
    d_gain: 3.4
    limit_err_p: 1.0
    limit_sum: 16.5 # N for clamping thrust force
    limit_p: 10 # m / s^2
    limit_i: 15 # m / s^2
    limit_d: 10 # m / s^2
    landing_err_z: -0.55

  yaw:
    limit_sum: 6.0 # N for clamping thrust force
    limit_p: 4.0
    limit_i: 4.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: false

  # LQI gain generator
  lqi:
    gain_generate_rate: 15.0
    gyro_moment_compensation: true
    clamp_gain: true

    roll_pitch_p: 1000
    roll_pitch_i: 10
    roll_pitch_d: 100

    yaw_p: 100
    yaw_i: 0.5
    yaw_d: 50

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1

mrac:
  log_rate: 10
  mrac_ratio: [1.0,1.0,0.0]
  k1m: [500,500,0.2]
  k2m: [200,200,0.8]
  K1: [5.0,5.0,2.0]
  K2: [10.0,10.0,2.0]
  kappa: [0.000001,0.000001,0.000001,0.0000001,0.0000001,0.0000001,2.0,2.0]
  sigma: [0.1,0.1,0.01,0.1,0.1,0.1,0.0,0.0]
  attitude_p: 1.0

  takeoff_wait_time: 5