aerial_robot_control_name: aerial_robot_control/delta_controller

controller:
  control_verbose: false
  torque_allocation_matrix_inv_pub_interval: 0.02
  wrench_allocation_matrix_pub_interval: 0.1
  use_sr_inv: false
  sr_inv_weight: 0.1
  hovering_approximate: false
  gimbal_lpf_factor: 1.0 # don't set to 0
  realtime_gimbal_allocation: true
  wrench_estimate_flag: true

  rolling_minimum_lateral_force: 0.2
  steering_mu: 2.0
  full_lambda_mode: true

  lambda_weight: 1.0
  d_gimbal_center_weight: 2.0
  d_gimbal_weight: 2.0
  gimbal_d_theta_max: 0.7
  d_lambda_max: 10.0
  ipopt_max_iter: 100

  xy:
    p_gain: 4.0
    i_gain: 0.5
    d_gain: 2.5
    limit_sum: 4.0
    limit_p: 12.0
    limit_i: 12.0
    limit_d: 12.0

  z:
    p_gain: 5.0
    i_gain: 1.5
    d_gain: 2.5
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0
    limit_i: 25.0
    limit_d: 25.0
    force_landing_descending_rate: -0.5

  roll_pitch:
    start_rp_integration_height: 0.01

  roll:
    p_gain: 15.0
    i_gain: 0.5
    d_gain: 2.0
    limit_sum: 50.0
    limit_p: 50.0
    limit_i: 50.0
    limit_d: 50.0

  pitch:
    p_gain: 15.0
    i_gain: 0.5
    d_gain: 2.0
    limit_sum: 50.0
    limit_p: 50.0
    limit_i: 50.0
    limit_d: 50.0

  yaw:
    p_gain: 4.0
    i_gain: 2.0
    d_gain: 6.0
    limit_err_p: 4.0
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

    need_d_control: true

standing_controller:
  gravity_compensate_ratio: 1.0
  xy:
    p_gain: 1.5
    i_gain: 0.0
    d_gain: 2.5

  z:
    p_gain: 20.0
    i_gain: 1.5
    d_gain: 2.5

  roll:
    p_gain: 4.0
    i_gain: 0.025
    d_gain: 2.0

  pitch:
    p_gain: 6.0
    i_gain: 0.1
    d_gain: 3.0

  yaw:
    p_gain: 2.0
    i_gain: 0.1
    d_gain: 1.0

rolling_controller:
  gravity_compensate_ratio: 0.0
  xy:
    p_gain: 1.5
    i_gain: 0.0
    d_gain: 2.5

  z:
    p_gain: 20.0
    i_gain: 1.5
    d_gain: 2.5

  roll:
    p_gain: 16.0
    i_gain: 0.1
    d_gain: 5.0

  pitch:
    p_gain: 6.0
    i_gain: 0.1
    d_gain: 3.0

  yaw:
    p_gain: 2.0
    i_gain: 0.1
    d_gain: 1.0
