# Teleop Basic Param

flight_navigation_plugin_name: aerial_robot_navigation/spider/walk_navigation

navigation:
  xy_control_mode: 0
  # World Pos Control Mode: 0
  # World Vel Control Mode: 2
  # Local Vel Control Mode: 3
  # Attitude Control Mode: 4

  verbose: false
  takeoff_height: 0.6
  outdoor_takeoff_height: 1.5

  # teleop operation
  max_target_vel: 0.5
  joy_target_vel_interval: 0.005  # 0.2 / 20 = 0.01, 0.005 ~ 0.01  m/s
  joy_target_z_interval: 0.02
  max_target_yaw_rate: 0.1 #  0.05
  teleop_local_frame: fc

  cmd_vel_lev2_gain : 2.0
  nav_vel_limit : 1.0

  gain_tunning_mode: 0
  max_target_tilt_angle: 0.2

  # gps waypoint
  gps_waypoint_threshold: 3.0
  gps_waypoint_check_du: 1.0

  # walk
  walk:
    raise_angle: 0.2
    raise_converge_thresh: 0.05
    lower_touchdown_thresh: 0.1
    constant_angle_thresh: 0.02
    check_interval: 0.1
    converge_time_thresh: 0.5

    failsafe:
      baselink_rot_thresh: 0.2
      opposite_raise_leg_thresh: 0.2

    simulation: false
    simulated_joint_lpf_rate: 0.2

    pattern:
      total_cycle: 5
      stride: 0.2 # stride for individual leg [m]
      move_leg_joint_err_thresh: 0.05 # check the convergence of joint motion in joint_yaw [rad]
      converge_du: 0.5 # [s]
      baselink_converge_thresh: 0.05 # check the convergence of baselink [m]
      front_leg_raise_ratio: 2.0 # the ratio to enlarger the raise angle for front leg
      reset_leg_end: false # use the actual state (e.g., joint angles) to reset leg ends
      reset_baselink: false # use the actual state (e.g., joint angles) to reset baselink
      debug: false
      debug_legs: 4
