aerial_robot_control_name: aerial_robot_control/fwddyn_mpc_controller

mpc:
  num_nodes: 50
  max_iter: 2
  max_init_iter: 400
  dt: 0.05
  num_threads: 4
  com_track_weight: [50000.0, 50000.0, 1000000.0]
  centroidal_momentum_weight: [10000, 10000, 10000, 10000, 10000, 1000]
  control_weight: 1.0
  thrust_reg_weight: 1.0
  thrust_barrier_weight: 10.0
  delta_thrust_max: 100000.0
  verbose: true
  verbose_log_duration: 1.0
  diag_pub_duration: 0.1
  x_state_weight: [0, 0, 0, 10000, 10000, 100000,
                   1000.0, 1000.0, 1000.0, 1000.0,            # gimbal1, 2
                   100000.0, 100000.0,                        # head, tail
                   1000.0, 1000.0,                            # gimbal3
                   0, 0, 0, 0, 0, 0,
                   500.0, 500.0, 500.0, 500.0,                 # gimbal1, 2
                   100.0, 100.0,                              # head, tail
                   500.0, 500.0]                              # gimbal3

  x_ref: [0, 0, 0, 0, 0, 0, 1,
          0, 0, 0, 0,
          0, 0,
          0, 0,
          0, 0, 0, 0, 0, 0,
          0, 0, 0, 0,
          0, 0,
          0, 0]
