servo_controller:
  gimbals:
    ctrl_pub_topic: servo/target_states
    torque_pub_topic: servo/torque_enable
    angle_sgn: -1
    angle_scale: 0.001534
    zero_point_offset: 2047

    simulation:
      pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
      init_value: 0
      type: effort_controllers/JointPositionController

    controller1:
      id: 1
      name: gimbal1_roll

    controller2:
      id: 2
      name: gimbal1_pitch

    controller3:
      id: 3
      name: gimbal2_roll

    controller4:
      id: 4
      name: gimbal2_pitch

    controller5:
      id: 5
      name: gimbal3_roll

    controller6:
      id: 6
      name: gimbal3_pitch