on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: ros_build_test
    strategy:
      fail-fast: false
      matrix:
        include:
          - ROS_DISTRO : melodic
            DOCKER_IMAGE : ubuntu:bionic
          - ROS_DISTRO : noetic
            DOCKER_IMAGE : ubuntu:focal
          - ROS_DISTRO : one
            DOCKER_IMAGE : ubuntu:jammy
    steps:
      - name: Setup OS
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
      - name: Setup Git
        run: |
          sudo apt-get install -y git
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: script
        if: matrix.DOCKER_IMAGE
        run: |
          export REPOSITORY=http://packages.ros.org/ros/ubuntu
          export REPOSITORY_NAME=${PWD##*/}
          docker run --rm -i -v $PWD:$PWD -e "CI_SOURCE_PATH=$PWD" -e REPOSITORY_NAME -e REPOSITORY -e "HOME=$HOME" -e "ROS_DISTRO=${{ matrix.ROS_DISTRO }}"  ${{ matrix.DOCKER_IMAGE }} sh -c "cd $PWD; /bin/bash .travis.sh"
