on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: ros_o_build_test
    strategy:
      fail-fast: false
    steps:
      - name: Setup OS
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y

      - name: Setup Git
        run: |
          sudo apt-get install -y git

      - name: Install ROS-O
        run: |
          sudo apt-get install -y vim less ca-certificates sudo bash-completion python3-pip git tmux python-is-python3
          pip3 install catkin-tools
          echo "deb [trusted=yes] https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one-unstable/repository ./" | sudo tee /etc/apt/sources.list.d/v4hn_ros-o-builder.list
          sudo apt update
          sudo apt install -y python3-rosdep2
          echo "yaml https://raw.githubusercontent.com/v4hn/ros-o-builder/jammy-one-unstable/repository/local.yaml debian" | sudo tee /etc/ros/rosdep/sources.list.d/1-v4hn_ros-o-builder.list
          rosdep update
          sudo apt-get install -y ros-one-desktop-full

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
