servo_controller:
  joints:
    angle_sgn: 1
    angle_scale: 0.00076699
    zero_point_offset: 2047
    torque_scale: 0.01 # TODO: update to correct scale

    # for simulation
    simulation:
      pid: {p: 50.0, i: 0.4, d: 2.0}
      init_value: 2.094
      type: effort_controllers/JointPositionController

    controller1:
      id: 1
      name: joint1
    controller2:
      id: 3
      name: joint2

  gimbals:
    no_real_state: false # true if there is no servo state from real machine
    angle_sgn: -1
    angle_scale: 0.00230209525
    zero_point_offset: 2047

    controller1:
      id: 0
      name: gimbal1
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0.0
        type: effort_controllers/JointPositionController

    controller2:
      id: 2
      name: gimbal2
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0.0
        type: effort_controllers/JointPositionController

    controller3:
      id: 4
      name: gimbal3
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0.0
        type: effort_controllers/JointPositionController
