<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="block" >

  <xacro:property name="block_x" value="1.0"/>
  <xacro:property name="block_y" value="0.3"/>
  <xacro:property name="block_z" value="2.0"/>
  <xacro:property name="mass" value="0.4"/>

  <link name="block">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${1 / 3 * (block_y * block_y + block_z * block_z) * mass}" ixy="0.0" ixz="0.0"
          iyy="${1 / 3 * (block_z * block_z + block_x * block_x) * mass}" iyz="0.0"
          izz="${1 / 3 * (block_x * block_x + block_y * block_y) * mass}"/>
    </inertial>
    <collision>
      <!-- <origin xyz="${block_x / 2} ${block_y / 2} ${block_z / 2}"/> -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${block_x} ${block_y} ${block_z}"/>
      </geometry>
    </collision>
    <visual>
      <!-- <origin xyz="${block_x / 2} ${block_y / 2} ${block_z / 2}"/> -->
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${block_x} ${block_y} ${block_z}"/>
      </geometry>
    </visual>
  </link>

  <gazebo reference="block">
    <mu1 value="0.8"/>
    <mu2 value="0.8"/>
  </gazebo>

 <gazebo reference="block">
      <material>Gazebo/Red</material>
 </gazebo>

</robot>
